### ISSUE TITLE
user profile mynd

### ISSUE THREAD

**Issue by SovietMan** [piratar/wasa2il#143]
var að uploada nýrri mynd og hún ákvað að snúa sér til vinstri.
direct linkur á myndina sýnir hana rétt, en ekki profile stillingar síðan.
direct link: https://x.piratar.is/uploads/userimg_1287a1f7133c2701239ee55965bbe482a3167937.jpg
profile: https://x.piratar.is/accounts/profile/SovietMan/

**Comment by baldurjonsson** [comment]
Direct linkurinn sýnir myndina líka á hlið í Windows Phone

**Comment by helgihg** [comment]
After a bit of research, it seems that this is a problem with different software treating EXIF information in different ways. It's not a problem in Wasa2il but probably either the browser or the image software used to create the image. The proper solution to this problem is fixing the orientation in the uploaded image.
