### ISSUE TITLE
Add an internationalization and localization (i18n) guide/howto

### ISSUE THREAD

**Issue by PeterTheOne** [piratar/wasa2il#151]
For example: How would I go about doing a German translation?

**Comment by PeterTheOne** [comment]
There seems to be a project on https://crowdin.com/project/wasa2il

**Comment by bjornlevi** [comment]
https://docs.djangoproject.com/en/1.10/topics/i18n/translation/

see .po files

**Comment by PeterTheOne** [comment]
Does crowdin use up-to-date data? Can someone download/import the German translation from there? Or give me the rights to do so? @bjornlevi @smari

**Comment by PeterTheOne** [comment]
Yay, the readme was updated.. https://github.com/piratar/wasa2il#contributing

Anyone willing to update https://crowdin.com/project/wasa2il ? I can't even download a .po file from there.. :/

**Comment by slim** [comment]
@PeterTheOne hey peter, did you translate it in German? We need the German translation for our instance (still not online)

**Comment by PeterTheOne** [comment]
@slim there is a translation on crowdin, that seems to be kind of complete. I expect the source not to be up to date, but it would be a good start if we could download it. so no.

**Comment by helgihg** [comment]
The instructions being requested are beyond the scope of this project. It's translated like any other Django project. I'm sure there are nice tutorials online, but for what it's worth, here's a really, really short tutorial, given a command line:

$ python manage.py makemessages -l de # "de" For German
$ [favorite-editor] wasa2il/locale/de/LC_MESSAGES/django.po # Again, "de" for German
...translate some strings...
$ python manage.py compilemessages # Compiles the translations

If this doesn't help, then you should seek instructions elsewhere on how to translate Django projects in general. It's not really good use of anyone's time to create a translation tutorial per Django project.

The stuff on Crowdin is outdated. The translations that were available aren't even included in the official distribution anymore, because they were essentially useless after all the changes that have been done to the software for the past few years.

To make matters worse, the Crowdin link above is probably referring to Smari's repository, whereas this one is a fork and has long since become quite a different beast from Smari's code base.

I'd strongly recommend starting a German translation from scratch by using the official Git repository here, and translating in the manner described above.

I'd be quite happy to assist interested translators into German, so I'm not closing this issue quite yet, even though this is beyond the reach of the project. Can @slim and @PeterTheOne tell me if what I just wrote makes any sense? I'm not quite sure what technical know-how is available here. :)

**Comment by PeterTheOne** [comment]
Ok, thanks.. At least we have a decision now to drop the old translation :P

**Comment by slim** [comment]
Hello @helgihg thanks, it makes sense :) I could use your help on other issues not related to this one. how can I contact you? (already following you on twitter)

**Comment by helgihg** [comment]
I've sent contact details to @slim, so I'm closing this issue now. :)
