### ISSUE TITLE
Allow candidates to express "highest accepted position"

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#190]
You cannot really force someone to take a high seat on a ballot, simply because some people aren't comfortable with the prospect of full-time parliament work or other types of responsibility (but might be OK being a backup or a "supporting candidate" in one of the lower positions on a ballot).

As a result in most primaries, candidates are given the option to "take a lower position" after the counting has taken place.

It should be possible to automate this process by asking candidates what is the highest position they are willing to accept, and take that into account automatically as a 2nd pass after the initial Schulze count.

**Comment by BjarniRunar** [comment]
Note that if implemented, this may obliviate the need to allow candidates to withdraw (issue #120), since they can simply set their "highest position" to something below the plausible threshold for ending up in parliament or whatever position is being voted for.

This would be a major improvement, since really is unacceptable for voters that the ballot changes mid-election. And this data could be exposed to voters in the interface, so they can see which candidates are willing to take real responsibility.

**Comment by biggboss83** [comment]
> Disallowing people from withdrawing also removes the need for recounts...
What if the candidate withdraws after the ballot has been finalized? Or is later found out to be ineligible for the ballot in question? Would that require a recount?

Additionally, "lowest accepted position" could be implemented. If withdrawing after the elections would require a recount, knowing this preference in advance could be beneficial.

**Comment by BjarniRunar** [comment]
@biggboss83  Lowest accepted position would be a misfeature in my mind. People have valid reasons for not wanting to be near the top (limited time, other obligations), but not wanting to be near the bottom is pure ego and I don't see why we should care about or encourage such silliness.

However, having discussed the "disallow removal" idea with the people managing the elections, it turns out that's not workable in practice. We can't force someone to stay on the ballot if they don't like it, so we'll always need to support withdrawls one way or another. If wasa2il refuses to support them, that just means extra manual post-processing.

**Comment by helgihg** [comment]
Let me confuse matters, or possibly simplify them.

Candidates don't know beforehand which seat they are comfortable with, since it may also depend on which other candidates are higher. Maybe they don't realize until afterward how they feel about the result. In any case, they are legally allowed to refuse a seat, so there's no point in debating that point. The only question is whether Wasa2il should support that as a feature or not.

So here's an idea. When an election result is known, an email is sent to candidates declaring their seat, with two links, one for accepting and one for rejecting. Those who accept take their seats, and those who reject it, lose their seats and the list goes upward. (I really cannot see why the ballots should be re-counted if someone rejects a seat; it's probably the most undesirable feature of Schulze and there is no reason to implement it - much rather to eliminate it). A superuser or polity officer should also be able to declare on their behalf whether they accept their seats, so that users who don't read their emails while everyone is waiting in anticipation don't hold up the election results unnecessarily.

This doesn't seem too difficult to implement, if everyone agrees on the method. In my opinion, this should have nothing to do with recounts. Recounts should be possible if they can reasonably be implemented, but I don't see them having anything to do with someone refusing to their seat.

**Comment by BjarniRunar** [comment]
Yuck. If people can't work with the other members of their own party, wtf are they doing running for parliament where they will have to work with people from polar opposite universes?  I just really don't see why we would encourage or condone that kind of childishness.

**Comment by BjarniRunar** [comment]
In any case, people will alwatys be able to withdraw completely, and we'd have the data on file to build a new ballot automatically. But letting people move up or down based on where other people ended up seems really wrong.

**Comment by BjarniRunar** [comment]
... and the recount thing would not be a problem at all, if the system actually had all the data it needs to give us a complete final result. The problems we have today have to do with the fact that some of the data is in meatspace, and some is in wasa2il, and then we need this weird manual back-and-forth between the two, mediated by a technician, in order to come to a conclusion.

**Comment by helgihg** [comment]
Whether the reasons are childish or not is beside the point; the point is that people don't know whether they'll accept their seats until after the election. The system doesn't care why they make whatever choice they make.

Not sure I understand this (or if we're possibly not talking about the same thing): "But letting people move up or down based on where other people ended up seems really wrong."

People can only bump themselves down regardless of reason. I'm not aware of anyone being able to bump themselves up, or any suggestion that they should be able to, which sort of confuses me.

Let me state what you're talking about, and tell me if I'm getting it right:

Once an election finishes, and there's a result, a candidate decides to NOT accept their seat (for whatever reason, childish or otherwise). Then, enough information is still stored, presumably ballots disconnected from users, for the system to recalculate the ballots without the user who rejected their seat. Then, when a final list is complete, the ballots are finally deleted. Is this what you're talking about?

**Comment by BjarniRunar** [comment]
Ballots are not currently deleted, just anonymized. Anonymization can happen immediately after the election completes, we don't need to know who voted for what in order to recount.

But aside from that, yes. If the system knows what is the highest position a candidate is willing to take on, recounts and generating a final list which takes candidate's wishes into account can happen automatically and instantly every time someone withdraws. If the system had this data, the only manual work we would need post-election is collecting signatures and filing paperwork.

**Comment by BjarniRunar** [comment]
(assuming people accepted this as a workable system, this is much more of a social thing than a computer thing... I'm getting a fair bit of pushback, people are so wedded to the idea that candidates need to be asked and given lots of opportunities and encouragement to change their mind ;-) )

**Comment by BjarniRunar** [comment]
The "moving up" happens hypothetically if you accept the premise that candidates should be given the opportunity to move down based on who else is on the ballot. Then if someone above them withdraws, it stands to reason they should be asked again, since things have changed, no? Which means they might accept a higher seat than before. People were seriously considering shenanigans like this last time, where every withdrawl was supposed to trigger asking everyone all the questions again. And, if we don't get people to express an actual opinion at some point, then any time someone withdraws (e.g. because of an illness or whatever), you have to go ask everyone below them all over again.

At some point people say "this is silly" and stop asking. I'm just saying we should do that as early as possible.

**Comment by BjarniRunar** [comment]
FWIW, at least some (the ones who were initially sceptical, most have been silent) of the folks who are running the current elections (Kjördæmasamráð) have agreed that this would be a good way to do things.

**Comment by helgihg** [comment]
It seems to me that this should be resolved by doing two things.

1. Fix the stupid bylaws that demand a recount when someone rejects their seat.

2. Allow candidates to reject their seats, thereby bumping everoyne below them up by one seat.

Objections?

**Comment by helgihg** [comment]
@smari and I have convened and decided that the proper solution to this involved bylaw change and does not currently require a technical solution. This is therefore closed for now.
