### ISSUE TITLE
Kjósa "með eða á móti"

### ISSUE THREAD

**Issue by bjornlevi** [piratar/wasa2il#43]
Þegar mál er í kosningu er textinn:
"Kjósa: með eða á móti þessu máli" - gefur möguleikana "já" og "nei". Þetta getur valdið ruglingi þar sem valmöguleikarnir eru ekki "með" og "á móti". Það gæti skilist á þann hátt að notandi vilji kjósa eða ekki kjósa. Semsagt; "nei, ég vil ekki kjósa".

Þegar hafa verið gerðar nokkrar ábendingar varðandi þetta orðalag, best væri að skýra það betur :)

**Comment by gsmari2** [comment]
Ég legg til að textinn á tökkunum þrem verði:
[ Með ]   [ Tek ekki afstöðu ]  [ Á móti ]

**Comment by helgihg** [comment]
Ég skal rumpa þetta af þegar 'bjornlevi' er búinn að samþykkja nýjustu
breytingarnar sem ég var að pull-request-a.

**Comment by helgihg** [comment]
I've come to disagree with this. I like the terminology "Yes", "Abstain" and "No". ("Já", "Sitja hjá", "Nei" in Icelandic.)

**Comment by helgihg** [comment]
Having discussed with Stjáni, we're leaving this the way it is. There is no inherent improvement in changing the phrasing, and it's more likely to confuse rather than explain anything. For example, the words are "Aye" and "Nay" in many places in the English world, instead of "in favor" or "against".
