### ISSUE TITLE
Should we use tags and add version number to the footer?

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#51]
(Nice to have)
So we can see which version is in production.
Or maybe there is another way?

**Comment by bjornlevi** [comment]
Yeah, nice to have. Could help some developers setting up the same version that is running on production. Don't really see the need though.

Prioritize for, "have nothing else to do and this looks like fun"

**Comment by viktorsmari** [comment]
Agreed. 
Maybe the admins add labels to issues for nicer ordering/grouping?
When they have nothing better to do :+1:

**Comment by 7oi** [comment]
I've actually done something similar recently. Fairly easy job, should take only a few minutes.

There's a nice module called **bumpversion** that handles version bumping nicely that can be added to requirements.txt. It would update the version in all the relevant places along with adding a tag in git. It can bump major/minor/patch versions along with custom stuff.

**Comment by viktorsmari** [comment]
I did this recently with a Ruby project, very nice to have :D

**Comment by 7oi** [comment]
To be able to do this, though, we'd need to agree on what type of versioning system to use:

- versioning by date?
- v{major}.{minor}.{patch}?
- something else?

...and which version wasa2il is actually at currently accordingly.

**Comment by viktorsmari** [comment]
For starters, the **git commit hash** would be nice, then you could verify that production  `www.x.is/version` or similar is running a specific commit

**Comment by helgihg** [comment]
I support using a version number. Hashes and dates are awful. Dates don't fit into people's brains the way version dates does (when ever do you say "I'm running Xenomorph version 19th February 2008"?). Hashes are the absolute worst option in my opinion. They should be used for something like Git logs but never for versioning.

We should start with something that we're going to stick with, rather than do something for starters and then change later. Not only is it unlikely that we'll ever change it if we're too busy now, but on top of that the mere change itself will cost in terms of confusion and change in organization.

Django's way of versioning is the best method in my opinion: X.Y.Z. The first number denotes major number, the second is the minor number, and the third are revisions which can be expected to be compatible given that the major and minor remain the same.

**Comment by anarchodin** [comment]
[Semver?](http://semver.org/)

**Comment by helgihg** [comment]
@anarchodin "Software using Semantic Versioning MUST declare a public API. This API could be declared in the code itself or exist strictly in documentation. However it is done, it should be precise and comprehensive."

That quickly went from a problem to another problem. ;)

**Comment by anarchodin** [comment]
The solution to any given problem is a bigger problem. That's how we get progress. :)

**Comment by 7oi** [comment]
...or we could just go highly logical on this and do:
1.x -> 2.x -> 3.0 -> 3.1x -> NT 3.x -> 95 -> NT 4.0 -> 98 -> 2000 -> ME -> XP -> Vista -> 7 -> 8 -> 10 -> covfefe

I do like the semver way, though, in spite of the whole documented public API problem. It presents a nice and clear definition of what each version bump entails.

...but determining at what version wasa2il is now could be a bit tricky.

Hash and date versioning are the easiest, of course, except that:
- Hash versioning seems a bit crappy to me as there's nothing descriptive about it. You can't read anything into it without following the git commit hash, and still that doesn't give you a clear picture of the scale of changes made or compatibility between versions unless you study the git log thoroughly.
- Date versioning at least gives you a feeling of the age of the version, but that's about it. It gives you no sense of compatibility between versions or the scale of changes between them either.

**Comment by helgihg** [comment]
Hashes are awful. They're awful. They're horrible. They are death. Let's really not use hashes. Really.

Dates give a hint of the age, indeed, however, they only tell you the last time something was built. It also gives the wrong impression that you should be going by when the particular instance that you have was built, rather than where it is in its development cycle. They're also just more clumsy in terms of comparison.

I strongly believe we should stick with an X.Y.Z model, but I don't see a reason to complicate matters by trying to abide to some particular standard like Semver, if it creates more problems than it solves. The X.Y.Z is not patented or anything, so we can use it without going fullblown Semver.

Where the code is right now is easy. It's at 0.8.7.

**Comment by viktorsmari** [comment]
I like hashes for only one use case, a developer can easily know which commit is in production.

I don't have experience with versioning, but is it easy to forget to 'bump' a version when you push a commit and deploy to production? If a developer has done some work, pushes to github and pushes to production but does not bump the version?

I have had issues before when I think a master branch is in production, when it is not. I have no SSH access to the machine so there is no way for me to find out - can versioning **guarantee** that won't happen?

Other then that, the version number is the obvious choice. But what about having both?

Example output from x.is/version:
`
08sdf8897dgf6sd8gf769d  
version 0.8.7
`

**Comment by 7oi** [comment]
Agreed. In fact, at my day job we use our own take on semver as well, basically reserving:
- major versions (**x**.y.z) for major changes in functionality, whether UI, serverside or both
- minor versions (x.**y**.z) for noticeable changes/additions that don't really have much impact on the project as a whole rather isolated parts
- patches (x.y.**z**) for bugfixes and tiny things that only serve to improve existing behaviour.

I think that's a sensible adaptation of semver... We're also implementing autoversioning through our CI so that our release branches trigger it automatically, but that's a whole different project. ;)

I like how easy it was to come up with the version.

**Comment by 7oi** [comment]
Well, of course displaying both is also a possibility, but using git tags is basically like using prettier hashes as each tag is basically just a shortcut to the commit that represents the state of the project at that time. So really there shouldn't be any need for both...

**Comment by helgihg** [comment]
Well, what I find important is that when asked the question: "Which version are you using?", the user should find it easy to read, say and remember. Version numbers work just fine and dandy for that. And I can't see a reason to use anything else, frankly. :) The date is irrelevant, the hash is a monster.

**Comment by viktorsmari** [comment]
Can a developer whose pull request has been merged, now simply verify that his code is on the server by using the version nr in the footer?

**Comment by helgihg** [comment]
I'm marking this as complete, since we're using Bumpversion now. Thanks, @7oi !

@viktorsmari : Yes, by comparing the version with the corresponding tag in the repository.
