### ISSUE TITLE
Prevent people from voting if their ballots won't be counted

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#84]
Currently, people may cast votes that are ultimately ignored.

This is very impolite, we should fix it so people are told up front that they cannot vote, and why.

**Comment by BjarniRunar** [comment]
On second thought, this may actually be unworkable in practice. We may need to instead use the following pattern:

1) WARN the user if their vote is not going to be counted, but allow them to vote
2) Allow 1-2 days after election closes, for excluded users to petition for their ballots to be counted
3) Count votes

The reason for this, is that sometime rules are not machine-enforceable. For example, if a user lives abroad, their last legal residence in Iceland is used to determine which constituancy they can vote in. There is no way for wasa2il to know about this sort of thing in advance, it will always need to be manually handled by a human admin/moderator.

Combined with the fact that realistically, most people won't plan ahead and won't realize their vote isn't going to be counted until the last minute. If we want to allow these people a chance to petition for inclusion in the election, we need a delay between closing and counting.

Hmm!

**Comment by BjarniRunar** [comment]
Note, this is a problem both on Issues and Elections.

**Comment by BjarniRunar** [comment]
I'm working on this.

**Comment by BjarniRunar** [comment]
Re-opening this, as the same (or equivalent) work may need to be done for issues.

**Comment by stjanigunnars** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prevent people from voting if their ballots won't be counted](https://trello.com/c/vUv4pzq2/6-prevent-people-from-voting-if-their-ballots-wont-be-counted)

**Comment by helgihg** [comment]
1. I finished this, but much had already been done.

2. If an election was running, it notified the user that the user could not vote. However, if it was still in the process of giving users the chance to run in the election, it used to only warn the user about not being able to run (if that was indeed the case). I changed it so that it warns the user BOTH whether they can run or vote. So a user who can neither vote nor run will be warned about both until the election opens. At that point the user is only warned about not being able to vote (since no one can run anymore at that point anyway).

3. The warning labels were changed from firy-red ("danger") to warning-yellow. Both prettier but also more in line with the nature of the information. (Arguably. Hey! Let's argue about this!)
