### ISSUE TITLE
Implement Single Sign-On Client

### ISSUE THREAD

**Issue by BjarniRunar** [piratar/wasa2il#98]
After discussing with a bunch of people, it seems there's agreement that making wasa2il completely delegate authentication to Icepirate would reduce user confusion.

Currently, users need to understand that access to wasa2il doesn't happen automatically after they join the party; if icepirate were responsible for authentication that point of confusion would go away.

The question of which tech to use for this is an open one. This also implies moving the Icekey verification code out of wasa2il and into icepirate (which also seems like the right thing to do).

**Comment by BjarniRunar** [comment]
This would probably make #94 unnecessary.

**Comment by PeterTheOne** [comment]
Can this be done while preserving the possibility to use it without icepirate?

**Comment by bjornlevi** [comment]
That should be fairly easy, defaulting to standard django authentication if
settings for another authentication system are missing. That's standard
django stuff to define a custom authentication backend.

On Tue, Jul 5, 2016 at 11:11 AM, Peter Grassberger <notifications@github.com

**Comment by BjarniRunar** [comment]
This is probably not going to happen before the elections, it's too complicated and therefore risky whether I'd get it done. I think long-term it's still the right thing to do, but more research is needed.

Instead, see #113 for an easier way to solve the usability issues.

**Comment by helgihg** [comment]
As @BjarniRunar mentioned, more research is needed.

Moving anything from Wasa2il to IcePirate is probably the wrong choice in my opinion. In fact, IcePirate should much rather be relieved of its current authentication duties rather than gaining more. Note that the only "authentication" that IcePirate performs is asking new members to verify their email addresses. Other than that, it doesn't do any authentication, and it wasn't designed to do any.

But in fact, the only confusion that I can imagine, is the fact that people have to verify their emails twice, if they first register for the party (via website -> IcePirate), and then again when creating an account in Wasa2il. Besides that, I cannot think of anything that might simplify the process, assuming that we want IceKey-verification in Wasa2il but not when joining the party on the website.

I believe that the proper way forward on this is to rethink the website->IcePirate registration process, and how it relates to Wasa2il, much rather than moving anything from Wasa2il to IcePirate.

**Comment by helgihg** [comment]
This is complicated and assumes design decisions that will not be taken in the foreseeable future. In particular, things are more likely to be moved from IcePirate to Wasa2il than the other way around.
